name: feature-01
run-name: ${{github.actor }} is deploying gh-pages
on:
  push:
    branches:
      - feature-01
jobs:
  ci-feature-01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: npx ng build --configuration=production --base-href="/${{ github.event.repository.name}}/"
      - run: yarn run lint
      - run: yarn run test:ci
